---
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  prefer-const: error
